### ISSUE TITLE
need pgview webui 

### ISSUE THREAD

**Issue by Liuzhj** [zalando/pg_view#102]
dear team,

i need to use pgview to monitor own pg db .
i want to know the pgview webui release time ? 
look up it's usefull, thank you very much . 

https://user-images.githubusercontent.com/1443395/37088392-7be43462-21fd-11e8-8ae2-e7fa2d3b2853.png

![image](https://user-images.githubusercontent.com/14147011/75361168-da3cc600-58f1-11ea-9db3-ec4f8e18cd17.png)

**Comment by CyberDem0n** [comment]
This UI is using [bg_mon](https://github.com/CyberDem0n/bg_mon) as a backend.
In the bg_mon repo there is a rudimentary UI (bg_mon.html). It is maybe not so beautiful but fully functional.

Please pay attention that you'll have to add bg_mon into shared_preload_libraries and restart postgres. It might sound scary, but I consider it very stable, we run it on about 2000 clusters without issues.

**Comment by Liuzhj** [comment]
@CyberDem0n 
thank you very much .
i have some question, how to management and monitor multiple pg instance ?
maybe i have 10 single pg instance, and have 20 pg clusters with 3 members of patroni .

> we run it on about 2000 clusters without issues

i want to know how to management 2000 clusters . it's so terrible for me now , please help me , thank you very much again.

**Comment by Liuzhj** [comment]
i was down the source code and try to build for install.
occur some warning , it's can be ignore?  Is it necessary to solve? 
![image](https://user-images.githubusercontent.com/14147011/75459900-b8a81100-59bb-11ea-8147-3aa698315f6a.png)

**Comment by CyberDem0n** [comment]
These are warnings. You can ignore them.
