### ISSUE TITLE
doesn't work on python3

### ISSUE THREAD

**Issue by ilrico** [zalando/pg_view#15]
hi, since python3 is becoming mainstream, what about porting it from current release ? i'm sure it would be appreciated.
thx for this project anyway.

**Comment by alexeyklyukin** [comment]
Hi,

pg_view is compatible with python3 since ffc94568b8fe7d9173a2a8100c9fefd815e04d82, kudos to @CyberDem0n

**Comment by hjacobs** [comment]
yeah, Python3 everywhere!
