### ISSUE TITLE
postgres as default user and database when autodetection

### ISSUE THREAD

**Issue by rjuju** [zalando/pg_view#16]
Hello,

When no configuration file is provided to pg_view, all the autodetection mechanism is done with "postgres" for user and database (see psycopg2.connect calls in main() and can_connect_with_connection_arguments() functions).

I think it would be better to do like standard postgresql clients, meaning detecting $PGUSER and $PGDATABASE and failback to system username if the environment variables are not set. That would simplify using pg_view when user can't connect with those default values (which is usually my case), but I agree it may not be the most common case.

Would you welcome a patch to change that behaviour ?

Regards.

**Comment by alexeyklyukin** [comment]
Hi Julien,

On Fri, Jun 19, 2015 at 11:02 PM, Julien Rouhaud <notifications@github.com>
wrote:

> Hello,
>
> When no configuration file is provided to pg_view, all the autodetection
> mechanism is done with "postgres" for user and database (see
> psycopg2.connect calls in main() and
> can_connect_with_connection_arguments() functions).
>
> I think it would be better to do like standard postgresql clients, meaning
> detecting $PGUSER and $PGDATABASE and failback to system username if the
> environment variables are not set. That would simplify using pg_view when
> user can't connect with those default values (which is usually my case),
> but I agree it may not be the most common case.
>

Makes sense. The auto detection is pretty much tailored for Zalando
use-case...


> Would you welcome a patch to change that behaviour ?
>

Absolutely!

Kind regards,
Oleksii

**Comment by rjuju** [comment]
Hi Oleksii,

Thanks for the quick answer, and I'm glad you welcome this change!

I just sent a pull request to implement it.

As I'm not a python developper, feel free to make any change if there was any issue I didn't spot with this patch.

Best regards.

**Comment by alexeyklyukin** [comment]
Hi Julien,

The patch looks good, I've merged your pull request.
Thank you very much!
