### ISSUE TITLE
Distribute pg_view via PyPI

### ISSUE THREAD

**Issue by hjacobs** [zalando/pg_view#19]
Distributing pg_view as a PyPI package (installable via PIP) would make it even easier for people to try it out or adopt it :-)

**Comment by valgog** [comment]
Very good idea!

**Comment by hjacobs** [comment]
First version uploaded: https://pypi.python.org/pypi/pg-view

**Comment by LappleApple** [comment]
This was done -- I vote on closing out this issue

**Comment by hjacobs** [comment]
IMHO this is not really done, the latest package upload is from June 2015: https://pypi.python.org/pypi/pg-view

**Comment by LappleApple** [comment]
What's the next step?

**Comment by alexeyklyukin** [comment]
I have just released the new version https://pypi.python.org/pypi/pg-view. Let's close this issue.
