### ISSUE TITLE
ERROR messages in log Column X is not optional, but input row has no value for it

### ISSUE THREAD

**Issue by spritchard** [zalando/pg_view#27]
When I run pg_view 1.2.0, I get a number of error messages in the log file of the form:

> Column X is not optional, but input row has no value for it 

The problem appears to be that the first time that the df data is used the data returned is empty. On subsequent occasions the data is present, and there are no further errors.

I've looked at the code and it appears at line 1181, instead of:

        for pname in PartitionStatCollector.DATA_NAME, PartitionStatCollector.XLOG_NAME:
            result[pname] = self._transform_input(df_out[pname], self.df_list_transformation)

it should be:

        for pname in PartitionStatCollector.DATA_NAME, PartitionStatCollector.XLOG_NAME:
            if pname in df_out:
                result[pname] = self._transform_input(df_out[pname], self.df_list_transformation)

This follows the same pattern as the code for du_out at line 1820.

It turns out that the error messages don't affect the functioning of pg_view, however I only found that out by digging through the code - I was initially concerned that the data displayed by pg_view might not be accurate and complete.

Steve Pritchard

**Comment by spritchard** [comment]
Correction to line number - should be 1811. Apologies.

**Comment by hjacobs** [comment]
Thanks for reporting!

**Comment by spritchard** [comment]
I've realised the fix isn't quite as simple as I thought! In further testing I found that I was still getting the error messages. The reason was that df_out =
>  {'xlog': [], 'data': []}

So "pname in df_out" is true, which means that self._transform_input(...) - with df_out[pname] empty.

I next tried replacing "if pname in df_out:" with
> if df_out[pname]:

but I then got:

>  File "pg_view.py", line 1815, in refresh
>    logger.info('result[' + pname + '] = ' + pformat(result[pname]));
>  KeyError: 'data'

i.e. the call to self.get_io_data(...) that follows needs to have result[pname] populated.

I've now got:

            if df_out[pname]:
                 result[pname] = self._transform_input(df_out[pname], self.df_list_transformation)
            else:
                 result[pname] = {'dev': None, 'space_left': None, 'space_total': None}

and then line 1820 changed to:

            if du_out[pname]:

(as some of the error messages were from processing the du output.

This seems to fix the problem.

Alternatively, self._transform_input(...) could be modified to handle the case of an empty list without reporting errors. 

Steve

**Comment by hjacobs** [comment]
I guess @alexeyklyukin has to check this :-)

**Comment by alexeyklyukin** [comment]
Hi,

Thanks for reporting this and researching the root cause. 
The original purpose for those messages were detecting the edge cases where the kernel on the machine doesn't provide necessary information (since pg_view is reading a lot from /proc files). Apparently, something went wrong here, I'll take a look.

**Comment by alexeyklyukin** [comment]
@spritchard Thank your for the diagnostics, I pushed a simple fix (6f505b3b1a02251ec9f7139c6b909bd3a4115692), changing the transformation functions to act in a more sane way. Please, reopen the issue if you still have a problem with this fix.

**Comment by spritchard** [comment]
Many thanks for addressing this so quickly. I've tested the new version (6f505b3) and I no longer get the error messages.
