### ISSUE TITLE
Minor version of Postgres is not displayed

### ISSUE THREAD

**Issue by kmoppel** [zalando/pg_view#30]
Version info shown in the below row could be extended or maybe would be even nice to show the full version() output in the bottommost line next to pg_view version info.

mydb 9.3 master database connections: 149 of 500 allocated,                7 active

**Comment by a1exsh** [comment]
> bottommost line next to pg_view version info.
That would be nice.  Then maybe we should remove the version from per-db status header...

**Comment by a1exsh** [comment]
Actually, the bottom line would not work, since there might be a number of clusters running on a single host and pg_view will try to inspect them all.

**Comment by a1exsh** [comment]
Quick test shows that the full version() isn't really helpful, it only takes extra space for little valuable info.  See PR #32 for a simpler solution.

**Comment by kmoppel** [comment]
Thanks @a1exsh !
