### ISSUE TITLE
Fit the bottom line menu to 80 cols

### ISSUE THREAD

**Issue by a1exsh** [zalando/pg_view#31]
With my current version (1.2.0) the bottom line menu doesn't fit into standard default terminal width.  I think we could use less verbose description in the menu and provide full description in the help screen:

    s: system f: freeze u: units a: autohide t: trim r: realtime h: Help    v.1.2.0

Thoughts?

**Comment by alexeyklyukin** [comment]
Works for me with 80x25 window, what's your standard size?

**Comment by a1exsh** [comment]
It does now, because it was addressed by this commit: https://github.com/zalando/pg_view/commit/6e3fcdc1391ab76f6c03dac6fe1fc2d91eb691a6 :)

Closing this issue.

**Comment by alexeyklyukin** [comment]
Thank you!
