### ISSUE TITLE
pg_view should accept connection string/URI or the usual set of postgres client -h,-p,-U,-d options on command line

### ISSUE THREAD

**Issue by a1exsh** [zalando/pg_view#39]
I'm surprised it does not, in order to specify a connection one has to create a config file first?

**Comment by alexeyklyukin** [comment]
The idea was that it should auto detect all PostgreSQL instances running on the machine, but yes, being able to specify individual connections would be an improvement.

**Comment by a1exsh** [comment]
Would it also be possible to run it remotely and skip all the /proc stuff?  I would still find it useful, e.g. now I'm in a docker container which only has psql-9.1 with no \watch command.  I thought I'd use pg_view to monitor pg_stat_activity, but no luck.  The DB itself RDS, so I can't run pg_view on the DB host.

**Comment by a1exsh** [comment]
For now emulating with a shell loop: `while true; do echo '<query>;'; sleep 5; done | psql ... ` ;-)

**Comment by alexeyklyukin** [comment]
No, it's not possible at the moment to run pg_view remotely, although it's a use case I would like to address in the future.

**Comment by alexeyklyukin** [comment]
Fixed at https://github.com/zalando/pg_view/pull/40
