### ISSUE TITLE
Don't die if connection to one of the monitored servers is lost

### ISSUE THREAD

**Issue by a1exsh** [zalando/pg_view#49]
If pg_view is used to monitor a number of clusters on a single screen and we lose connection to just one of them (due to restart by the administrator, for example), pg_view dies with connection error.

It would be nice if we could continue to display data for the servers we still have the connections to, and ideally, resume the lost one once the server is back.

**Comment by kmoppel** [comment]
+1

**Comment by a1exsh** [comment]
See #51

**Comment by a1exsh** [comment]
Merged :-)
