### ISSUE TITLE
Needs Maintainers File, Contributor Guidelines

### ISSUE THREAD

**Issue by LappleApple** [zalando/pg_view#62]
LMK if you need help adding.

**Comment by LappleApple** [comment]
@alexeyklyukin @hjacobs @a1exsh @CyberDem0n @valgog Hi again, checking in on this. Who might be maintaining this now?

**Comment by alexeyklyukin** [comment]
I'm maintaining this, but not doing any active development.

**Comment by LappleApple** [comment]
@alexeyklyukin OK. I'll make the file
