### ISSUE TITLE
Problem with PG 9.3

### ISSUE THREAD

**Issue by DaniloE** [zalando/pg_view#7]
Hi there,

i tried to run pg_view with PG 9.3, but there i always got the message "No suitable PostgreSQL instances detected, exiting...". I found the reason for the issue and I think it's the easiest way, when i post you my diff:

```
--- pg_view.py_doesntwork   2013-12-20 16:09:19.000000000 +0100
+++ pg_view.py  2013-12-20 16:18:36.000000000 +0100
@@ -2677,7 +2677,7 @@
             logger.error('failed to read {0}'.format(stat_file_name))
             continue
         # read PostgreSQL processes. Avoid zombies
-        if len(stat_fields) < STAT_FIELD_START_TIME + 1 or stat_fields[STAT_FIELD_PROCESS_NAME] != '(postgres)' \
+        if len(stat_fields) < STAT_FIELD_START_TIME + 1 or stat_fields[STAT_FIELD_PROCESS_NAME] != '(postmaster)' \
             or stat_fields[STAT_FIELD_STATE] == 'Z':
             if stat_fields[STAT_FIELD_STATE] == 'Z':
                 logger.warning('zombie process {0}'.format(pid))
@@ -2703,7 +2703,7 @@
                 if cmd_line:
                     fields = cmd_line.split('\x00')
                     if len(fields) > 2:
-                        data_dir = fields[2]
+                        data_dir = fields[4]
                         postmaster_data_dirs.append(data_dir)
                         postmaster_pids.append(pid)
     return dict(zip(postmaster_data_dirs, postmaster_pids))
```

I hope that helps, if it's a configuration-problem on my instance, sorry for the post.
I'm using the official repo from PG for the Installation and started the instance via Init-Script, if this is necessary.

**Comment by sgnatjuk** [comment]
Hi!
I have a similar problem. When you run the pg_view - I get the error:

unable to connect to PostgreSQL cluster at /var/lib/pgsql/9.2/data using any of the detected connection options: {'unix': [('/tmp', '5432')], 'tcp6': [('0000:0000:0000:0000:0000:0000:0000:0000', '5432')], 'tcp': [('0.0.0.0', '5432')]}
No suitable PostgreSQL instances detected, exiting...
hint: use -v for details, or specify connection parameters manually in the configuration file (-c)
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pg_view-1.2.0-py2.6.egg/pg_view.py", line 3326, in main
    sys.exit(1)
SystemExit: 1

Please help solve the problem!
I hope very much for your help.
Thank you,
with respect
Gnatjuk Sergey

**Comment by alexeyklyukin** [comment]
Looks like your cluster is not listening to tcp connections, and that your unix_socket_directory is set to something outside of /tmp, so basically, pg_view is unable to detect your connection credentials. You can set them.
You can either change your unix_socket_directory to point to /tmp, enable TCP connections (and make sure pg_view can connect via pg_hba.conf), or write a configuration file for pg_view, specifying how to connect, and pass it with -c option.

**Comment by sgnatjuk** [comment]
Thank's
But ...

I use similar programs:
1. pg_activity -U postgres
2. https://github.com/gleu/pgstats
And it works ??
Do not tell me, for my case should look Conf. file ?

**Comment by sgnatjuk** [comment]
pg_activity -p 5432 -U postgres -d work-test

**Comment by sgnatjuk** [comment]
т.е. другие программулинки работают. Я не большой спец в nix, можете дать рекомендации для начинающих, как правильно поднастроить систему (если в этом дело). Может системные переменные какие-нибудь посмотреть или еще чего??

**Comment by alexeyklyukin** [comment]
What is the value of unix_socket_directories (or unix_socket_directory, if your PostgreSQL version is below 9.3), and listen_addresses? You can get them by asking the running server:

show unix_socket_directories
show listen_addresses.

The configuration file format is described in the documentation.
```
[DEFAULT]
port=5432
host=/path/to/your/unix/socket/directory
```

**Comment by sgnatjuk** [comment]
Hi!
Please tell me if I could talk with his you in their native language?
I am afraid that I can not describe the problem in detail.
I use a special patched version postgreskl to 1S8.
Link - https://www.postgrespro.ru/products/1c_build
Most likely this problem.
In Conf. File specified: #unix_socket_directory = '' # (change requires restart)

The parameter description is written:
An empty value specifies not listening on any Unix-domain sockets, in which case only TCP/IP sockets can be used to connect to the server. The default value is normally /tmp, but that can be changed at build time. This parameter can only be set at server start.

listens to port 5432
I connect on the TСP IP and using this port, but with other programs.
Help me please.

**Comment by alexeyklyukin** [comment]
Please, connect to the running PostgreSQL server and run:

show unix_socket_directory;
show listen_addresses;
show port;

and post the output.

If I were to guess, I'd say that your unix_socket_directory points to /var/run/postgresql, as your directory layout looks similar to the standard PostgreSQL on Debian/Ubuntu. pg_view has no means of finding it out, so it fails (your libpq library, being compiled with the same settings as PostgreSQL server, likely just uses default settings to connect, I think pg_view should also try this if nothing else works)

I think you can try a hack, get the latest pg_view from github and supply connection parameters with -d option:
pg_view.py -d "host=/var/run/postgresql port=5432 user=postgres dbname=postgres"

**Comment by sgnatjuk** [comment]
1. show unix_socket_directory;
[root@PostgreSQL-1C8 pg-view-1.2.0]# psql -U postgres
psql (9.2.14)
Введите "help", чтобы получить справку.

postgres=# show unix_socket_directory;
 unix_socket_directory
-----------------------

(1 строка)

postgres=#
2. show listen_addresses;
postgres=# show listen_addresses;
 listen_addresses
------------------
 *
(1 строка)

postgres=#

3. show port;
postgres=# show port;
 port
------
 5432
(1 строка)

postgres=#

4. [root@PostgreSQL-1C8 pg-view-1.2.0]# ./pg_view.py -d "host=/var/run/postgresql port=5432 user=postgres dbname=postgres"
Usage: pg_view.py [options]

pg_view.py: error: no such option: -d
[root@PostgreSQL-1C8 pg-view-1.2.0]#

**Comment by alexeyklyukin** [comment]
Please, get the *latest* pg_view from github (git clone https://github.com/zalando/pg_view.git)
Run it as a postgres user, not as a root.

**Comment by sgnatjuk** [comment]
how to remove pg-view-1.2.0

**Comment by alexeyklyukin** [comment]
I believe you can do pip uninstall pg_view, if it was installed from pip, but you don't need to remove it, just clone the new one, and run it with python ./pg_view.py [options] from inside the newly cloned pg_view directory.

**Comment by alexeyklyukin** [comment]
Actually, if you tried to run pg_view under the root user previously, try to run it as a postgres user first.

**Comment by sgnatjuk** [comment]
this is the correct reference? - https://pypi.python.org/packages/source/p/pg-view/pg-view-1.2.0.tar.gz

**Comment by alexeyklyukin** [comment]
This is the link to 1.2.0 that you  already have on your server. 
Please, get the latest version from github by doing git clone https://github.com/zalando/pg_view.git

**Comment by sgnatjuk** [comment]
Sorry for dullness, but you can not just give you a link to download the archive

**Comment by sgnatjuk** [comment]
./pg_view.py -d "host=/var/run/postgresql port=5432 user=postgres dbname=postgres" work
thanks

**Comment by alexeyklyukin** [comment]
There is no archive link, since the github master changes are not packaged yet.

**Comment by alexeyklyukin** [comment]
Actually, I think pg_view can do better, in particular, try to use the defaults libpq is compiled with. I'll file a new issue, thank you for reporting.
